### ISSUE TITLE
Linux binary error on launch: "Error loading ... libpython3.8.so.1.0: dlopen: ... libm.so.6: version `GLIBC_2.35' not found

### ISSUE THREAD

**Issue by jxyzn** [mastotron/mastotron#12]
```
(1452) Error loading Python lib '/tmp/_MEI95gDRS/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.35' not found (required by /tmp/_MEI95gDRS/libpython3.8.so.1.0)
```
That's the only output I get when launching MastotronApp in a Chrome Linux VM, even after installing these:
```
sudo apt-get install build-essential libgl1-mesa-dev
sudo apt install python3-pip
pip3 install pyqt5 pyqtwebengine
pip3 install pywebview           
pip3 install pywebview[qt]
```

More environment details:

```
$ uname -a
Linux penguin 5.10.153-20432-gaa06ea936644 #1 SMP PREEMPT Tue Jan 10 19:07:58 PST 2023 x86_64 GNU/Linux
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by 87113** [comment]
Hi, I just try to launch it on Ubuntu 22.10 and I got kind of the same error,  both with the bin https://github.com/quadrismegistus/mastotron/releases/download/v1.0.0/Mastotron-linux.zip and the pip install. 

Basically this is the error : `wwebview.util.WebViewException: You must have either QT or GTK with Python extensions installed in order to use pywebview.`

Here the full traces : [https://pastebin.mozilla.org/vdprGkT8](https://pastebin.mozilla.org/vdprGkT8)

Your app looks great on the presentation. Thank's already for your work :)

**Comment by quadrismegistus** [comment]
Hey there, thanks! Does running mastotron via pip work? If you `pip3 install -U mastotron && mastotron`? Or updated instructions here: https://github.com/quadrismegistus/mastotron/edit/main/README.md#linux ?

**Comment by jxyzn** [comment]
Chasing down other unmentioned dependencies, this is as close as I get:
```
$ mastotron 
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "/home/jason/.local/lib/python3.9/site-packages/webview/guilib.py", line 16, in import_gtk
    import webview.platforms.gtk as guilib
  File "/home/jason/.local/lib/python3.9/site-packages/webview/platforms/gtk.py", line 26, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
[pywebview] Using Qt 5.15.2

DevTools listening on ws://127.0.0.1:8228/devtools/browser/9dff69b2-a2ec-4d4b-a06b-b7a26017b476


                 /eeeeeeeeeee\ 
   /RRRRRRRRRR\ /eeeeeeeeeeeee\ /RRRRRRRRRR\ 
  /RRRRRRRRRRRR\|eeeeeeeeeeeee|/RRRRRRRRRRRR\ 
 /RRRRRRRRRRRRRR +++++++++++++ RRRRRRRRRRRRRR\ 
|RRRRRRRRRRRRRR ############### RRRRRRRRRRRRRR| 
|RRRRRRRRRRRRR ######### ####### RRRRRRRRRRRRR| 
 \RRRRRRRRRRR ######### ######### RRRRRRRRRR/ 
   |RRRRRRRRR ########## ######## RRRRRRRR| 
  |RRRRRRRRRR ################### RRRRRRRRR| 
               ######     ###### 
               #####       ##### 
               #nnn#       #nnn#

                MASTOTRON v0.4.5                

             http://localhost:1789              

        (Visit this URL in your browser.        
      It's been copied to your clipboard.)      

Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:8228
js: Uncaught ReferenceError: change_node_color is not defined
http://localhost:8228
Traceback (most recent call last):
  File "/home/jason/.local/lib/python3.9/site-packages/webview/platforms/qt.py", line 144, in show_inspector
    BrowserView.instances[uid].raise_()
KeyError: 'master-inspector'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jason/.local/lib/python3.9/site-packages/webview/platforms/qt.py", line 573, in on_load_finished
    self.view.show_inspector()
  File "/home/jason/.local/lib/python3.9/site-packages/webview/platforms/qt.py", line 150, in show_inspector
    window = Window('web_inspector', title, url, '', 700, 500, None, None, True, False,
TypeError: __init__() missing 1 required positional argument: 'localization'
Aborted (core dumped)
```

**Comment by quadrismegistus** [comment]
Ok, round 2! Let's abandon the windowing altogether since that seems like it might take a minute to resolve. I just added a background only mode which means you'll just use your own browser to point to the URL (http://localhost:1789).

For those up to testing, do these new instructions here work? -->

https://github.com/quadrismegistus/mastotron#linux

**Comment by jxyzn** [comment]
pip update from github and --bg launch got it running, and I'm viewing it now.
Thanks!

**Comment by ocrampal** [comment]
pip install update git+https://github.com/quadrismegistus/mastotron
mastotron --bg 

Works now! Thanks ... inspiring ...

**Comment by quadrismegistus** [comment]
Closing to consolidate similar issues. See https://github.com/mastotron/mastotron/issues/22 now instead.
