### ISSUE TITLE
mastotron crashes while trying to load login URL

### ISSUE THREAD

**Issue by morganmay** [mastotron/mastotron#15]
I'm using the pip version of 1.0.0 on Arch Linux. When I try to load the login URL (http://localhost:1789) in Firefox, mastotron crashes with the following error:

```
js: Uncaught ReferenceError: change_node_color is not defined
http://localhost:8228
Traceback (most recent call last):
  File "/home/morgan/.local/lib/python3.10/site-packages/webview/platforms/qt.py", line 144, in show_inspector
    BrowserView.instances[uid].raise_()
KeyError: 'master-inspector'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/morgan/.local/lib/python3.10/site-packages/webview/platforms/qt.py", line 573, in on_load_finished
    self.view.show_inspector()
  File "/home/morgan/.local/lib/python3.10/site-packages/webview/platforms/qt.py", line 150, in show_inspector
    window = Window('web_inspector', title, url, '', 700, 500, None, None, True, False,
TypeError: Window.__init__() missing 1 required positional argument: 'localization'
[1]    2780105 IOT instruction (core dumped)  mastotron
```

**Comment by quadrismegistus** [comment]
Darn. So then even in Firefox / a separate browser, the localhost URL doesn't pull up mastodon? I'm installing an emulator now to help debug

**Comment by quadrismegistus** [comment]
does this work?

https://github.com/quadrismegistus/mastotron/issues/12#issuecomment-1426448334

**Comment by quadrismegistus** [comment]
Closing to consolidate similar issues. See https://github.com/mastotron/mastotron/issues/22 now instead.
