### ISSUE TITLE
Prebuilt linux binary not working

### ISSUE THREAD

**Issue by ChildishGiant** [mastotron/mastotron#8]
```
/etc/magic, 4: Warning: using regular magic file `/usr/share/misc/magic'
/usr/share/misc/magic, 39681: Warning: type `lemsdosdate	x		\b, last modified %s' invalid
/usr/share/misc/magic, 39682: Warning: type `lemsdostime	x		%s' invalid
/etc/magic, 4: Warning: using regular magic file `/usr/share/misc/magic'
/usr/share/misc/magic, 39681: Warning: type `lemsdosdate	x		\b, last modified %s' invalid
/usr/share/misc/magic, 39682: Warning: type `lemsdostime	x		%s' invalid
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "webview/guilib.py", line 16, in import_gtk
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "webview/platforms/gtk.py", line 25, in <module>
ModuleNotFoundError: No module named 'gi'
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "webview/guilib.py", line 29, in import_qt
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "webview/platforms/qt.py", line 34, in <module>
ModuleNotFoundError: No module named 'qtpy'
Traceback (most recent call last):
  File "cli.py", line 23, in <module>
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "cli.py", line 19, in cli
  File "mastotron/gui/app.py", line 416, in mainview
  File "mastotron/gui/app.py", line 467, in browse
  File "webview/__init__.py", line 129, in start
  File "webview/guilib.py", line 93, in initialize
webview.util.WebViewException: You must have either QT or GTK with Python extensions installed in order to use pywebview.
[6089] Failed to execute script 'cli' due to unhandled exception!
```
Seems like I need to install the right python libs but I also get an error when trying to install from source

```
[als@fedora Mastotron-linux]$ pip install git+https://github.com/quadrismegistus/mastotron
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/quadrismegistus/mastotron
  Cloning https://github.com/quadrismegistus/mastotron to /tmp/pip-req-build-v1vlaqng
  Running command git clone --filter=blob:none --quiet https://github.com/quadrismegistus/mastotron /tmp/pip-req-build-v1vlaqng
  Resolved https://github.com/quadrismegistus/mastotron to commit 6d7c9691d466a7a00afafd48603152a142fafa2c
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-v1vlaqng/setup.py", line 1, in <module>
          import mastotron as pkg
        File "/tmp/pip-req-build-v1vlaqng/mastotron/__init__.py", line 2, in <module>
          from .mastotron import *
        File "/tmp/pip-req-build-v1vlaqng/mastotron/mastotron.py", line 1, in <module>
          from .imports import *
        File "/tmp/pip-req-build-v1vlaqng/mastotron/imports.py", line 40, in <module>
          from mastodon.errors import MastodonNotFoundError, MastodonNetworkError
      ModuleNotFoundError: No module named 'mastodon'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by aral** [comment]
Just came over to report the same thing (on Fedora Silverblue).

**Comment by iGormilhit** [comment]
I tried to install from source, inside a python virtualenv and got this:

```bash
❯ pip install git+https://github.com/quadrismegistus/mastotron
Collecting git+https://github.com/quadrismegistus/mastotron
  Cloning https://github.com/quadrismegistus/mastotron to /tmp/pip-req-build-waqk8sek
  Running command git clone -q https://github.com/quadrismegistus/mastotron /tmp/pip-req-build-waqk8sek
  Resolved https://github.com/quadrismegistus/mastotron to commit 317abc290b3ba777f5cb8d2dc54e49c7a3cb94a4
    ERROR: Command errored out with exit status 1:
     command: /home/igor/.pyenv/versions/3.10.1/envs/mastotron/bin/python3.10 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-waqk8sek/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-waqk8sek/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-h0irapsd
         cwd: /tmp/pip-req-build-waqk8sek/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-waqk8sek/setup.py", line 1, in <module>
        import mastotron as pkg
      File "/tmp/pip-req-build-waqk8sek/mastotron/__init__.py", line 2, in <module>
        from .mastotron import *
      File "/tmp/pip-req-build-waqk8sek/mastotron/mastotron.py", line 1, in <module>
        from .imports import *
      File "/tmp/pip-req-build-waqk8sek/mastotron/imports.py", line 35, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
WARNING: Discarding git+https://github.com/quadrismegistus/mastotron. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 21.2.4; however, version 23.0 is available.
You should consider upgrading via the '/home/igor/.pyenv/versions/3.10.1/envs/mastotron/bin/python3.10 -m pip install --upgrade pip' command.
```

I'm surprised I didn't got the same missing module as @ChildishGiant :slightly_smiling_face:

**Comment by ocrampal** [comment]
Same!

**Comment by onezetty** [comment]
Same with me, I'm having this issue on Ubuntu 22.04: 

`❯ ./MastotronApp
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "webview/guilib.py", line 16, in import_gtk
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "webview/platforms/gtk.py", line 25, in <module>
ModuleNotFoundError: No module named 'gi'
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "webview/guilib.py", line 29, in import_qt
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "webview/platforms/qt.py", line 34, in <module>
ModuleNotFoundError: No module named 'qtpy'
Traceback (most recent call last):
  File "cli.py", line 23, in <module>
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "cli.py", line 19, in cli
  File "mastotron/gui/app.py", line 416, in mainview
  File "mastotron/gui/app.py", line 467, in browse
  File "webview/__init__.py", line 129, in start
  File "webview/guilib.py", line 93, in initialize
webview.util.WebViewException: You must have either QT or GTK with Python extensions installed in order to use pywebview.
[114369] Failed to execute script 'cli' due to unhandled exception!`

**Comment by quadrismegistus** [comment]
Thanks everyone!!!

Could people installing from pip try again? There was a bug!
Either `pip install -U mastodon` or `pip install git+https://github.com/quadrismegistus/mastotron`.

For people running the binary, – I took a look around, and could you try what's [recommended here](https://github.com/r0x0r/pywebview/issues/805#issuecomment-972673381)

```
sudo apt-get install build-essential libgl1-mesa-dev
pip3 install pyqt5 pyqtwebengine
pip3 install pywebview           
pip3 install pywebview[qt]
```

And then running the app binary again?

**Comment by iGormilhit** [comment]
@quadrismegistus Pip installation succeeded for me. Thanks!

**Comment by ThomasA** [comment]
Thanks for making this. I just saw your app on Mastodon.  
I have just tried running the binary in Ubuntu 22.04 and it fails the same way @onezetty reported above. Also after trying [your suggestion](https://github.com/quadrismegistus/mastotron/issues/8#issuecomment-1426201937) @quadrismegistus.

**Comment by ThomasA** [comment]
I have now also tried pip-installing it and it reports very similar errors:
```
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "/home/tari/miniconda3/envs/mastotron/lib/python3.10/site-packages/webview/guilib.py", line 16, in import_gtk
    import webview.platforms.gtk as guilib
  File "/home/tari/miniconda3/envs/mastotron/lib/python3.10/site-packages/webview/platforms/gtk.py", line 25, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "/home/tari/miniconda3/envs/mastotron/lib/python3.10/site-packages/webview/guilib.py", line 29, in import_qt
    import webview.platforms.qt as guilib
  File "/home/tari/miniconda3/envs/mastotron/lib/python3.10/site-packages/webview/platforms/qt.py", line 34, in <module>
    from qtpy import QtCore
  File "/home/tari/miniconda3/envs/mastotron/lib/python3.10/site-packages/qtpy/QtCore.py", line 15, in <module>
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5'
Traceback (most recent call last):
  File "/home/tari/miniconda3/envs/mastotron/bin/mastotron", line 8, in <module>
    sys.exit(cli())
  File "/home/tari/miniconda3/envs/mastotron/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/tari/miniconda3/envs/mastotron/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/tari/miniconda3/envs/mastotron/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tari/miniconda3/envs/mastotron/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/tari/miniconda3/envs/mastotron/lib/python3.10/site-packages/mastotron/cli.py", line 19, in cli
    mainview()
  File "/home/tari/miniconda3/envs/mastotron/lib/python3.10/site-packages/mastotron/gui/app.py", line 416, in mainview
    browse(app = app, func = main)
  File "/home/tari/miniconda3/envs/mastotron/lib/python3.10/site-packages/mastotron/gui/app.py", line 467, in browse
    return webview.start(
  File "/home/tari/miniconda3/envs/mastotron/lib/python3.10/site-packages/webview/__init__.py", line 129, in start
    guilib = initialize(gui)
  File "/home/tari/miniconda3/envs/mastotron/lib/python3.10/site-packages/webview/guilib.py", line 93, in initialize
    raise WebViewException('You must have either QT or GTK with Python extensions installed in order to use pywebview.')
webview.util.WebViewException: You must have either QT or GTK with Python extensions installed in order to use pywebview.
```

**Comment by morganmay** [comment]
I'm on Arch Linux. I had the same problem with both the pre-built binary and the pip package. After installing the recommended packages above, the pre-built version still fails to launch with the same errors, but the pip version runs.

**Comment by salarua** [comment]
Same error on Pop OS 22.04 with pip package:
```
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 142, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 257, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 109, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Soup' version '2.4', but '3.0' is already loaded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/salarua/.local/lib/python3.10/site-packages/webview/guilib.py", line 16, in import_gtk
    import webview.platforms.gtk as guilib
  File "/home/salarua/.local/lib/python3.10/site-packages/webview/platforms/gtk.py", line 35, in <module>
    from gi.repository import WebKit2 as webkit
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 144, in load_module
    raise ImportError(e)
ImportError: Requiring namespace 'Soup' version '2.4', but '3.0' is already loaded
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "/home/salarua/.local/lib/python3.10/site-packages/webview/guilib.py", line 29, in import_qt
    import webview.platforms.qt as guilib
  File "/home/salarua/.local/lib/python3.10/site-packages/webview/platforms/qt.py", line 34, in <module>
    from qtpy import QtCore
ModuleNotFoundError: No module named 'qtpy'
Traceback (most recent call last):
  File "/home/salarua/.local/bin/mastotron", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/salarua/.local/lib/python3.10/site-packages/mastotron/cli.py", line 19, in cli
    mainview()
  File "/home/salarua/.local/lib/python3.10/site-packages/mastotron/gui/app.py", line 416, in mainview
    browse(app = app, func = main)
  File "/home/salarua/.local/lib/python3.10/site-packages/mastotron/gui/app.py", line 467, in browse
    return webview.start(
  File "/home/salarua/.local/lib/python3.10/site-packages/webview/__init__.py", line 129, in start
    guilib = initialize(gui)
  File "/home/salarua/.local/lib/python3.10/site-packages/webview/guilib.py", line 93, in initialize
    raise WebViewException('You must have either QT or GTK with Python extensions installed in order to use pywebview.')
webview.util.WebViewException: You must have either QT or GTK with Python extensions installed in order to use pywebview.
```
With prebuilt binary:
```
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "webview/guilib.py", line 16, in import_gtk
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "webview/platforms/gtk.py", line 25, in <module>
ModuleNotFoundError: No module named 'gi'
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "webview/guilib.py", line 29, in import_qt
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "webview/platforms/qt.py", line 34, in <module>
ModuleNotFoundError: No module named 'qtpy'
Traceback (most recent call last):
  File "cli.py", line 23, in <module>
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "cli.py", line 19, in cli
  File "mastotron/gui/app.py", line 416, in mainview
  File "mastotron/gui/app.py", line 467, in browse
  File "webview/__init__.py", line 129, in start
  File "webview/guilib.py", line 93, in initialize
webview.util.WebViewException: You must have either QT or GTK with Python extensions installed in order to use pywebview.
[67539] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by quadrismegistus** [comment]
Thank you to everyone reporting!

For all those still having issues -- do the updated instructions here work?
https://github.com/quadrismegistus/mastotron/edit/main/README.md#linux

Let's abandon the prebuilt binary for now and focus on getting it running for you all via pip, since that seems to have had more success. That's what instructions above try to do

**Comment by ThomasA** [comment]
I have tried the updated instructions. At least it fails differently for me now:
```
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "/home/tari/miniconda3/envs/mastotron/lib/python3.10/site-packages/webview/guilib.py", line 16, in import_gtk
    import webview.platforms.gtk as guilib
  File "/home/tari/miniconda3/envs/mastotron/lib/python3.10/site-packages/webview/platforms/gtk.py", line 25, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
[pywebview] Using Qt 5.15.2
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: kan ikke åbne delt objektfil: Ingen sådan fil eller filkatalog (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: kan ikke åbne delt objektfil: Ingen sådan fil eller filkatalog (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: kan ikke åbne delt objektfil: Ingen sådan fil eller filkatalog (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
QGLXContext: Failed to create dummy context

DevTools listening on ws://127.0.0.1:8228/devtools/browser/f251ff36-acd6-4df9-9c1c-59da03d00be4
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
```

**Comment by ocrampal** [comment]
On Archllinux, KDE:

Traceback (most recent call last):
  File "/home/ocrampal/.local/bin/mastotron", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ocrampal/.local/lib/python3.10/site-packages/mastotron/cli.py", line 19, in cli
    mainview()
  File "/home/ocrampal/.local/lib/python3.10/site-packages/mastotron/gui/app.py", line 416, in mainview
    browse(app = app, func = main)
  File "/home/ocrampal/.local/lib/python3.10/site-packages/mastotron/gui/app.py", line 467, in browse
    return webview.start(
TypeError: start() got an unexpected keyword argument 'private_mode'

**Comment by onezetty** [comment]
Trying:

**pip install -U mastodon**
```
❯ pip install -U mastodon
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement mastodon (from versions: none)
ERROR: No matching distribution found for mastodon
```

**pip install git+https://github.com/quadrismegistus/mastotron**
```
❯ pip install git+https://github.com/quadrismegistus/mastotron
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/quadrismegistus/mastotron
  Cloning https://github.com/quadrismegistus/mastotron to /tmp/pip-req-build-8c_2hkac
  Running command git clone --filter=blob:none --quiet https://github.com/quadrismegistus/mastotron /tmp/pip-req-build-8c_2hkac
  Resolved https://github.com/quadrismegistus/mastotron to commit 32c7c85f68edcfa517c4b7c8c3107eb8b4fa8367
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Flask-Session in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (0.4.0)
Requirement already satisfied: IPython in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (8.10.0)
Requirement already satisfied: cogdb in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (3.0.4)
Requirement already satisfied: eventlet in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (0.33.3)
Requirement already satisfied: flask in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (2.2.2)
Requirement already satisfied: flask_socketio in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (5.3.2)
Requirement already satisfied: gevent in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (22.10.2)
Requirement already satisfied: gevent-websocket in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (0.10.1)
Requirement already satisfied: human_readable in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (1.3.2)
Requirement already satisfied: mastodon.py in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (1.8.0)
Requirement already satisfied: networkx in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (3.0)
Requirement already satisfied: pandas in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (1.5.3)
Requirement already satisfied: pyinstaller in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (5.7.0)
Requirement already satisfied: pyperclip in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (1.8.2)
Requirement already satisfied: pywebview in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (4.0.1)
Requirement already satisfied: scipy in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (1.10.0)
Requirement already satisfied: screeninfo in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (0.8.1)
Requirement already satisfied: simple-websocket in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (0.9.0)
Requirement already satisfied: sqlitedict in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (2.1.0)
Requirement already satisfied: tqdm in ./.local/lib/python3.10/site-packages (from mastotron==0.4.5) (4.64.1)
Requirement already satisfied: xxhash==3.2.0 in ./.local/lib/python3.10/site-packages (from cogdb->mastotron==0.4.5) (3.2.0)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3/dist-packages (from eventlet->mastotron==0.4.5) (1.16.0)
Requirement already satisfied: dnspython>=1.15.0 in ./.local/lib/python3.10/site-packages (from eventlet->mastotron==0.4.5) (2.3.0)
Requirement already satisfied: greenlet>=0.3 in ./.local/lib/python3.10/site-packages (from eventlet->mastotron==0.4.5) (2.0.2)
Requirement already satisfied: itsdangerous>=2.0 in ./.local/lib/python3.10/site-packages (from flask->mastotron==0.4.5) (2.1.2)
Requirement already satisfied: click>=8.0 in /usr/lib/python3/dist-packages (from flask->mastotron==0.4.5) (8.0.3)
Requirement already satisfied: Jinja2>=3.0 in ./.local/lib/python3.10/site-packages (from flask->mastotron==0.4.5) (3.1.2)
Requirement already satisfied: Werkzeug>=2.2.2 in ./.local/lib/python3.10/site-packages (from flask->mastotron==0.4.5) (2.2.2)
Requirement already satisfied: cachelib in ./.local/lib/python3.10/site-packages (from Flask-Session->mastotron==0.4.5) (0.10.2)
Requirement already satisfied: python-socketio>=5.0.2 in ./.local/lib/python3.10/site-packages (from flask_socketio->mastotron==0.4.5) (5.7.2)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from gevent->mastotron==0.4.5) (59.6.0)
Requirement already satisfied: zope.event in ./.local/lib/python3.10/site-packages (from gevent->mastotron==0.4.5) (4.6)
Requirement already satisfied: zope.interface in ./.local/lib/python3.10/site-packages (from gevent->mastotron==0.4.5) (5.5.2)
Requirement already satisfied: decorator in ./.local/lib/python3.10/site-packages (from IPython->mastotron==0.4.5) (5.1.1)
Requirement already satisfied: jedi>=0.16 in ./.local/lib/python3.10/site-packages (from IPython->mastotron==0.4.5) (0.18.2)
Requirement already satisfied: stack-data in ./.local/lib/python3.10/site-packages (from IPython->mastotron==0.4.5) (0.6.2)
Requirement already satisfied: backcall in ./.local/lib/python3.10/site-packages (from IPython->mastotron==0.4.5) (0.2.0)
Requirement already satisfied: traitlets>=5 in ./.local/lib/python3.10/site-packages (from IPython->mastotron==0.4.5) (5.9.0)
Requirement already satisfied: matplotlib-inline in ./.local/lib/python3.10/site-packages (from IPython->mastotron==0.4.5) (0.1.6)
Requirement already satisfied: pygments>=2.4.0 in ./.local/lib/python3.10/site-packages (from IPython->mastotron==0.4.5) (2.14.0)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.30 in ./.local/lib/python3.10/site-packages (from IPython->mastotron==0.4.5) (3.0.36)
Requirement already satisfied: pexpect>4.3 in /usr/lib/python3/dist-packages (from IPython->mastotron==0.4.5) (4.8.0)
Requirement already satisfied: pickleshare in ./.local/lib/python3.10/site-packages (from IPython->mastotron==0.4.5) (0.7.5)
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from mastodon.py->mastotron==0.4.5) (2.8.1)
Requirement already satisfied: python-magic in ./.local/lib/python3.10/site-packages (from mastodon.py->mastotron==0.4.5) (0.4.27)
Requirement already satisfied: requests>=2.4.2 in /usr/lib/python3/dist-packages (from mastodon.py->mastotron==0.4.5) (2.25.1)
Requirement already satisfied: blurhash>=1.1.4 in ./.local/lib/python3.10/site-packages (from mastodon.py->mastotron==0.4.5) (1.1.4)
Requirement already satisfied: numpy>=1.21.0 in /usr/lib/python3/dist-packages (from pandas->mastotron==0.4.5) (1.21.5)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas->mastotron==0.4.5) (2022.1)
Requirement already satisfied: altgraph in ./.local/lib/python3.10/site-packages (from pyinstaller->mastotron==0.4.5) (0.17.3)
Requirement already satisfied: pyinstaller-hooks-contrib>=2021.4 in ./.local/lib/python3.10/site-packages (from pyinstaller->mastotron==0.4.5) (2022.15)
Requirement already satisfied: proxy-tools in ./.local/lib/python3.10/site-packages (from pywebview->mastotron==0.4.5) (0.1.0)
Requirement already satisfied: bottle in ./.local/lib/python3.10/site-packages (from pywebview->mastotron==0.4.5) (0.12.23)
Requirement already satisfied: wsproto in ./.local/lib/python3.10/site-packages (from simple-websocket->mastotron==0.4.5) (1.2.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in ./.local/lib/python3.10/site-packages (from jedi>=0.16->IPython->mastotron==0.4.5) (0.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in ./.local/lib/python3.10/site-packages (from Jinja2>=3.0->flask->mastotron==0.4.5) (2.1.2)
Requirement already satisfied: wcwidth in ./.local/lib/python3.10/site-packages (from prompt-toolkit<3.1.0,>=3.0.30->IPython->mastotron==0.4.5) (0.2.6)
Requirement already satisfied: python-engineio>=4.3.0 in ./.local/lib/python3.10/site-packages (from python-socketio>=5.0.2->flask_socketio->mastotron==0.4.5) (4.3.4)
Requirement already satisfied: bidict>=0.21.0 in ./.local/lib/python3.10/site-packages (from python-socketio>=5.0.2->flask_socketio->mastotron==0.4.5) (0.22.1)
Requirement already satisfied: executing>=1.2.0 in ./.local/lib/python3.10/site-packages (from stack-data->IPython->mastotron==0.4.5) (1.2.0)
Requirement already satisfied: pure-eval in ./.local/lib/python3.10/site-packages (from stack-data->IPython->mastotron==0.4.5) (0.2.2)
Requirement already satisfied: asttokens>=2.1.0 in ./.local/lib/python3.10/site-packages (from stack-data->IPython->mastotron==0.4.5) (2.2.1)
Requirement already satisfied: h11<1,>=0.9.0 in ./.local/lib/python3.10/site-packages (from wsproto->simple-websocket->mastotron==0.4.5) (0.14.0)
❯ mastotron
zsh: command not found: mastotron
```
**sudo apt-get install build-essential libgl1-mesa-dev
pip3 install pyqt5 pyqtwebengine
pip3 install pywebview           
pip3 install pywebview[qt]**

```
❯ ./MastotronApp
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "webview/guilib.py", line 16, in import_gtk
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "webview/platforms/gtk.py", line 25, in <module>
ModuleNotFoundError: No module named 'gi'
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "webview/guilib.py", line 29, in import_qt
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "webview/platforms/qt.py", line 34, in <module>
ModuleNotFoundError: No module named 'qtpy'
Traceback (most recent call last):
  File "cli.py", line 23, in <module>
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "cli.py", line 19, in cli
  File "mastotron/gui/app.py", line 416, in mainview
  File "mastotron/gui/app.py", line 467, in browse
  File "webview/__init__.py", line 129, in start
  File "webview/guilib.py", line 93, in initialize
webview.util.WebViewException: You must have either QT or GTK with Python extensions installed in order to use pywebview.
[221993] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by quadrismegistus** [comment]
https://github.com/quadrismegistus/mastotron/issues/12#issuecomment-1426448334 can we try this new approach?

**Comment by miblodelcarpio** [comment]
--bg works beautifully for me. Thank you, @quadrismegistus!

**Comment by quadrismegistus** [comment]
Closing to consolidate similar issues. See https://github.com/mastotron/mastotron/issues/22 now instead.
